// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqKVJnyS3td0bMyOCLImt5quEfDBmib4',
    appId: '1:840957277955:web:533cbff4868e1f1d849b36',
    messagingSenderId: '840957277955',
    projectId: 'sinavvt-b8514',
    authDomain: 'sinavvt-b8514.firebaseapp.com',
    storageBucket: 'sinavvt-b8514.firebasestorage.app',
    measurementId: 'G-JHGELH7FCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUV5FfgR89xC9NHLqUlR5ULFaBgVwBnDY',
    appId: '1:840957277955:android:955109267fcbdaf4849b36',
    messagingSenderId: '840957277955',
    projectId: 'sinavvt-b8514',
    storageBucket: 'sinavvt-b8514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOfMAM_PpwQAlaZAey3bjv6LVnaTF1XU0',
    appId: '1:840957277955:ios:40c0e9bbcbc81ff2849b36',
    messagingSenderId: '840957277955',
    projectId: 'sinavvt-b8514',
    storageBucket: 'sinavvt-b8514.firebasestorage.app',
    iosBundleId: 'com.example.sinavv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOfMAM_PpwQAlaZAey3bjv6LVnaTF1XU0',
    appId: '1:840957277955:ios:40c0e9bbcbc81ff2849b36',
    messagingSenderId: '840957277955',
    projectId: 'sinavvt-b8514',
    storageBucket: 'sinavvt-b8514.firebasestorage.app',
    iosBundleId: 'com.example.sinavv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXqKVJnyS3td0bMyOCLImt5quEfDBmib4',
    appId: '1:840957277955:web:e5318386d1809080849b36',
    messagingSenderId: '840957277955',
    projectId: 'sinavvt-b8514',
    authDomain: 'sinavvt-b8514.firebaseapp.com',
    storageBucket: 'sinavvt-b8514.firebasestorage.app',
    measurementId: 'G-6ESJRZQS1H',
  );
}
